### ISSUE TITLE
Erro in Frost Cloud skill

### ISSUE THREAD

**Issue by gilvanoliveira7** [Gardios/ToS-Addons#4]
There is a error in elementalist skill. The attribute is wrong.

Sry for bad english
![download](https://cloud.githubusercontent.com/assets/16293332/16057773/8921fe2a-3249-11e6-8f1d-412af6bcd0e1.jpg)

screenshot: http://steamcommunity.com/sharedfiles/filedetails/?id=703779023

**Comment by Gardios** [comment]
As outlined [here](https://github.com/Gardios/ToS-Addons/issues/2), that's a bug IMC will have to deal with.
